# Generated by Django 3.1 on 2020-08-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_boast',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
